### PR TITLE
Hide student consultations2

### PR DESCRIPTION
**Pull request by 2351852**
##Description
I can remove the view of my consultations on the calendar
##Acceptance criteria
-On the student dashboard a button 'clear consultations on calendar appears'
-If consultations were made visible with 'show consultations on calendar button,' you can remove them using the clear button
-All consultations must disappear from the calendar
-But they are not deleted from the dataset

Note: end to end testing will come later on
##Story Points Expected:2

Closing https://github.com/witseie-elen4010/2023-group-lab-007/issues/54

### CODE REVIEW

**Review by RotendaM — COMMENTED** [review]
Functionality: Not Approved. Interfere with previous commits
Tests: Approved. Unnecessary
Documentation: Approved
Naming: Approved
Comments: Approved. Good!
Style: Approved.
Complexity: Approved

**Review by RotendaM — COMMENTED** [review]
Functionality: Not Approved. Interfere with previous commits
Tests: Approved. Unnecessary
Documentation: Approved
Naming: Approved
Comments: Approved. Good!
Style: Approved.
Complexity: Approved

**Review by RotendaM — COMMENTED** [review]
Functionality: Approved
Tests: Approved
Documentation: Approved
Naming: Approved
Comments: Approved
Style: Approved
Complexity: Approved

**Comment by bcgrahn** [comment]
Functionality: Approved
Tests: Approved. 
Documentation: Approved. No documentation was necessary for this story
Naming: Approved
Comments: Approved. Great work
Style: Approved.
Complexity: Approved. Its noteworthy to mention that the way a user needs to click on the consultation, then click the drop down list, and then click cancel is not user friendly. However it was discussed that cosmetics and styling will be improved on in the final sprint

**Pull request merged**
