### PR TITLE
Logs

### PR DESCRIPTION
**Pull request by bcgrahn**
## Description

A user must be able to access the log information

## Acceptance criteria
- A user should be able to view all actions as console logs with appropriate descriptions as well as who initiated the action when running the application on a local machine
- A user should be able to view all actions as logs with appropriate descriptions as well as who initiated the action via a live stream on azure
- A user can view the log history at /logs

## Functionality implemented but not limited to the user story
- Styling of more details page
- Styling of settings page
- Styling of lecturer dashboard
- Styling of not a member page
- Styling of more details page
- Styling of student dashboard
- Lecturer can only specify one consultation period per day
- Playwright tests
- Unit tests

## Points
2

### CODE REVIEW

**Review by RotendaM — COMMENTED** [review]
Picture Quality: Good.
Documentation: Approved
Style: Disapproved. Used semi-colons on too many occasions.
Comments: Approved. Satisfactory
Complexity: Approved.
Tests: No test required in documentation. Approved.
Functionality: Approved.

**Comment by bcgrahn** [comment]
I'll remove the semi-colons

**Review by 2351852 — COMMENTED** [review]
Documentation: Approved
Style: Disapproved. Check your use of semi colons
Comments: Approved. Although to make it excellent add a few more for your tests
Complexity: Approved.
Tests: Approved. Wonderful, lots of tests 
Functionality: Approved.

**Review by RotendaM — COMMENTED** [review]
Documentation: Approved
Style: Approved. 
Comments: Approved. Satisfactory
Complexity: Approved. 
Tests: Approved. Excellent work with the tests provided.
Functionality: Approved.

**Comment by bcgrahn** [comment]
Logging is now available when user navigates to /logs on the webpage

**Review by 2351852 — COMMENTED** [review]
Documentation: Approved
Style: Approved, thanks for fixing
Comments: Approved. 
Complexity: Approved.
Tests: Approved. 
Functionality: Approved.

**Review by sendr7 — APPROVED** [review]
Functionality: Approved. Accessible through \logs
Tests: Approved
Documentation: Approved
Naming: Approved. 
Comments: Approved.
Style: Approved. Style conventions met
Complexity: Approved.

**Comment by bcgrahn** [comment]
removed all semi-colons

**Pull request merged**
