### PR TITLE
Added lecturer calendar with default consultations.

### PR DESCRIPTION
**Pull request by Gilad-Kangisser**
Story ref: [[View their default-set consultation slots on calender (Lecturer)#20](https://github.com/witseie-elen4010/2023-group-lab-007/issues/20)]

 ## Description
- View the calendar with dummy consultations on the lecturer dashboard.

### Lecturer Dashboard

- User can view the lecturer dashboard.
- User can see the calendar of the current month.
- User can view different months on the calendar.
- User can press a button to show dummy consultations.

### CODE REVIEW

**Comment by sendr7** [comment]
Looks good. Accepting the request now

**Review by sendr7 — COMMENTED** [review]
Functionality: Approved
Tests: Denied. No testing present
Documentation: Approved
Naming: Approved
Comments: Approved
Style: Approved
Complexity: Approved

**Comment by 2351852** [comment]
Functionality: Looks good
Tests: Denied. Need to update tests
Documentation: Denied, please update the ADR to explain you calendar choice.
Naming: Approved
Comments: Approved, good use of comments so far
Style: Approved
Complexity: Approved

**Comment by 2351852** [comment]
Testing: One test added which is sufficient. Approved
Functionality: Approve
Documentation: Approve
Naming: Approved
Comments: Approved, good use of comments so far
Style: Approved
Complexity: Approved

**Pull request merged**
