### PR TITLE
Endofsprint2

### PR DESCRIPTION
**Pull request by bcgrahn**
End of sprint 2

### CODE REVIEW

**Review by sendr7 — APPROVED** [review]
Documentation is sufficient

**Review by 2351852 — COMMENTED** [review]
Scrum Board, updated. But do you not want the story board update as welll?

**Comment by bcgrahn** [comment]
Only required to do that in sprint 3's submission

**Comment by 2351852** [comment]
Then documentation is sufficient. It can be merged

**Pull request merged**
